[project]
name = "muffin-horsey"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "playwright>=1.52.0",
    "polars>=1.30.0",
]
